Fixed "INTERNAL ERROR!!! undefined method `upto' for (307/2):Rational" error
Certain settings of the .rdebugrc file, like in my case this:

	set listsize 25

Caused exception to appear when invoking the debugger:

	INTERNAL ERROR!!! undefined method `upto' for (307/2):Rational
	vendor/ruby/1.9.1/gems/debugger-1.1.3/lib/ruby-debug/commands/list.rb:79:in `display_list'
	vendor/ruby/1.9.1/gems/debugger-1.1.3/lib/ruby-debug/commands/list.rb:47:in `execute'

This commit fixes the error.